sudo: false

language: php
php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

after_success:
  - travis_retry php vendor/bin/coveralls
