language: php

sudo: false

matrix:
    include:
        - php: 5.6
    fast_finish: true

script: composer test

before_script: composer install

after_success:
  - travis_retry php vendor/bin/coveralls
